[package]
name = "xh-backend-lua"
version = "0.1.0"
edition = "2024"

[dependencies]
xh-engine.workspace = true
xh-reports.workspace = true
log.workspace = true
petgraph.workspace = true
serde.workspace = true
mlua = { version = "0.11.5", features = ["lua54", "serde", "send"] }
