[package]
name = "xh-backend-lua"
version = "0.1.0"
edition = "2024"

[dependencies]
log.workspace = true
petgraph.workspace = true
serde.workspace = true
thiserror.workspace = true
xh-engine.workspace = true
mlua = { version = "0.11.4", features = ["lua54", "serde", "macros", "async", "send"] }
