[package]
name = "xh-reports"
version = "0.1.0"
edition = "2024"

[features]
pretty = ["dep:owo-colors"]

[dependencies]
thiserror.workspace = true
educe.workspace = true
smol_str.workspace = true
owo-colors = { version = "4.2.3", optional = true }
smallvec = "1.15.1"
