[package]
name = "xh-archive"
version = "0.1.0"
edition = "2024"

[features]
std = ["blake3/std", "thiserror/std"]

[dependencies]
blake3.workspace = true
thiserror.workspace = true
bytes = "1.11.0"
zstd-safe = { version = "7.2.4", features = ["std"] }
