[package]
name = "xh-common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
xh-reports.workspace = true
bytes.workspace = true
blake3.workspace = true
fastrand.workspace = true
